// show_menu.h

#ifndef SHOW_MENU
#define SHOW_MENU
#include <Arduino.h>

void showMainMenu();
void showSensorListMenu();
void showSensorList();
void showSensorConfig();
void showSensorCategories();
void showSupportedSensor();
void showAddSensorOptions();
void showAddSensorSteps();
void showAddingSensor();
void showSuccessSensorAdd();
void showFailedSensorAdd();
void showActiveSensors();
void showRemoveSensorConfirmation();
void showSuccessSensorRemove();
void showCancelSensorRemove();
void showSettingsMenu();
void showBatteryMenu();
void showBatterySavingConfirmation();
void showBatterySavingActivated();
void showProfilesMenu();
void showSavingProfile();
void showProfileSaved();
void showDeleteProfileConfirmation();
void showDeletedProfile();
void showProfileOptionsMenu();
void showProfileList();
void showProfileSelected();
void showExportingProfile();
void showProfileExported();
void showImportProfileInstructions();
void showFoundProfileList();
void showSingleProfileFoundConfirmation();
void showMultipleProfileFoundConfirmation();
void showImportedProfile();
void showConnectivityMenu();
void showNodeConnectionMenu();
void showSearchingNodes();
void showNodesFound();
void showNodePairMenu();
void showNodeLocationRequest();
void showPairNodeConfirmation();
void showPairNode();
void showStationConnectMenu();
void showSearchingForStations();
void showStationsFound();
void showConnectingStation();
void showStationConnected();
void showPairedStationsList();
void showStationDisconnectConfirmation();
void showDisconnectingStation();
void showStationDisconnected();
void showStationMenu();
void showChipMenu();
void showCheckingInternet();
void showInternetConnection();

#endif